services:

  mu-web:
    build: ./Web
    container_name: mu-web
    env_file: .env
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
    depends_on:
      mu-sqlserver:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      mu-network:
        ipv4_address: 10.10.0.5
        
volumes:
  sqldata:
    name: mu-sqldata

networks:
  mu-network:
    driver: nat
    ipam:
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1
